name: flutter

on: 
  release: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' 
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
    
